# .github/workflows/auto-update-docs.yml
name: Automated Documentation Update

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write       # to push updated docs
  pull-requests: write  # to update the PR branch
  issues: read

jobs:
  update-docs:
    runs-on: ubuntu-latest
    # Skip if triggered by GH Actions bot or if head commit asks to skip docs
    if: >
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.pull_request.head.sha, '[skip docs]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR files
        id: pr-files
        run: |
          FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | \
            jq -r '[.[].filename] | @json')
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Create Devin Docs Update Session
        id: devin-docs
        env:
          DEVIN_API_KEY: ${{ secrets.DEVIN_API_KEY }}
          FILES_CHANGED: ${{ steps.pr-files.outputs.files }}
          UPDATE_PROMPT: |
            You are Devin Docs Assistant. Review the diffs for PR #${{ github.event.pull_request.number }} and update only the existing documentation files (under docs/) to reflect those code changes. Do not create new docs or modify code. Stop when docs are updated.

        run: |
          ESCAPED_PROMPT=$(echo "$UPDATE_PROMPT" | jq -Rs .)
          curl -s -X POST \
            -H "Authorization: Bearer $DEVIN_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"prompt\": $ESCAPED_PROMPT}" \
            "https://api.devin.ai/v1/sessions"

      - name: Wait for Devin session to finish
        # Poll GET /v1/sessions/{session_id} until status=='stopped'
        run: echo "⏳ Waiting for Devin to complete…"

      - name: Commit & Push Updated Docs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet --exit-code || (
            git commit -m "docs: update via Devin [skip docs]" &&
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          )
